### ISSUE TITLE
Remove paragraph around header tags

### ISSUE THREAD

**Issue by karbassi** [fannytan/fannytan.github.io#1]
The header elements (`<h1>`–`<h6>`)  are block elements like the paragraph element (`<p>`), but the header and paragraph elements can only have inline content inside of them, unlike other block elements like forms (`<form>`) and divs (`<div>`). Therefore, you can't nest headings inside paragraphs. And if you think about it, a heading really should never be in a paragraph.

Fix this by removing the paragraph elements around your header elements.

## For example:
https://github.com/fannytan/fanny.github.io/blob/82fbf9f2e636d931bc68854bfcdcdd9b3968778f/project1.html#L21

Would change from 
```html
<p id="Problem"><h3>Problem</h3></p>
```
to
```html
<h3 id="problem">Problem</h3>
```

There are other examples like this in your project.

**Comment by fannytan** [comment]
Oh, I see, heading or paragraph indeed...
I need to sleep more to avoid those kinds of stupid mistakes! Haha.

Thanks Ali
